---
image:
    publisher: MicrosoftWindowsServer
    offer: WindowsServer
    sku: 2022-datacenter-azure-edition
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - centralus
        - northcentralus
        - eastus
        - eastus2
        - southcentralus
        - westus
        - westus2
vm:
    size: Standard_F32s_v2
    tags:
        base_image: win2022642009azure
        worker_pool_id: win2022-64-2009
        sourceOrganisation: mozilla-platform-ops
        sourceRepository: ronin_puppet
        sourceBranch: cloud_windows
        deploymentId: d5dee60
        managed_by: packer
