---
image:
    publisher: MicrosoftWindowsServer
    offer: WindowsServer
    sku: 2022-datacenter-azure-edition
azure:
    managed_image_resource_group_name: rg-packer-through-cib
    managed_image_storage_account_type: Standard_LRS
    build_location: eastus
    locations:
        - centralus
        - northcentralus
vm:
    size: Standard_F16s_v2
    tags:
        base_image: win2022642009azure
        worker_pool_id: win2022-64-2009
        sourceOrganisation: mozilla-platform-ops
        sourceRepository: ronin_puppet
        sourceBranch: relops607
        deploymentId: 4c9a9c7
#        sourceBranch: bug1838725
#        deploymentId: d44b764
        managed_by: packer
